name: CI
on: [push]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to lightsail"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deploy.key
          chmod 600 ~/.ssh/deploy.key
          cat >>~/.ssh/config <<END
          Host deploy
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deploy.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USER }}
          SSH_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}

      - name: git pull
        run: ssh deploy 'cd live-chat && git pull'

      - name: install package
        run: ssh deploy 'npm i'

      - name: restart the server
        # if: ${{ always() }}
        run: ssh deploy 'pm2 restart 0'